
- name: Upload and run Python script
  hosts: ec2_instances
  gather_facts: false

  tasks:
    - name: Upload Python script
      copy:
        src: ../script.py
        dest: /home/ec2-user/script.py
        mode: '0755'

    - name: Run the script
      command: python3 /home/ec2-user/script.py
